### ISSUE TITLE
The link to the SNAPPER tutorial appears to be broken

### ISSUE THREAD

**Issue by henicorhina** [rbouckaert/speedemon#1]
Clicking on the link downloads a corrupted zip file

**Comment by rbouckaert** [comment]
Thanks for the bug report, but I tried and had no problem downloading the tutorial from https://github.com/BEAST2-Dev/beast-docs/releases/download/v1.0/snapper-delimitation-tutorial-2021.zip so I wonder what went wrong. What operating system are you using? What do you use to uncompress the zip file, and what error message are you getting?

**Comment by henicorhina** [comment]
The file was (and is) downloading just fine. The issue was unzipping it. Using the Mac OS archive utilities gave the following error (Unable to expand "snapper-delimitation-tutorial-2021.zip*. It is in an unsupported format.), but changing the file permissions and unzipping through the terminal (unzip) solved the problem just now. Thanks!

**Comment by rbouckaert** [comment]
Good to know. I can confirm that the archive utility behaves that way, and it seems a common problem when searching for the error message. If you think there is anything we can do about this, please let us know. Otherwise, I'll close the issue.

**Comment by henicorhina** [comment]
I guess you could add a quick sentence to the speedemon readme that the link is to a zipped archive that should be opened via command line utilities

**Comment by rbouckaert** [comment]
Good idea! The readme is updated now.
